'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''imgBtnPICol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnPICol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgBtnPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnPI As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnPhysicalInvCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnPhysicalInvCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgBtnPhysicalInv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnPhysicalInv As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnExportItemsCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnExportItemsCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgBtnExportItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnExportItems As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnOnlineSalesCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnOnlineSalesCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgBtnOnlineSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnOnlineSales As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HyperLinkPISummaryCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkPISummaryCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HyperLinkPISummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkPISummary As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLinkPysicalInvCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkPysicalInvCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HyperLinkPysicalInv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkPysicalInv As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLinkExportItemCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkExportItemCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HyperLinkExportItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkExportItem As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLinkOnlineSalesCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkOnlineSalesCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HyperLinkOnlineSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkOnlineSales As Global.System.Web.UI.WebControls.HyperLink
End Class
